"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ANALYTICS_EVENTS = exports.SESSION_EVENTS = exports.STORAGE_KEYS = void 0;
exports.STORAGE_KEYS = {
    ACCESS_TOKEN: "accessToken",
    REFRESH_TOKEN: "refreshToken",
    CAMPAIGN_TASK: "campaignTask",
    CURRENT_CAMPAIGN_TASK_TYPE: "currentCampaignTaskType",
    SOCIAL_CONNECT_TASK_MODAL: "isConnectTaskInitiated",
    SOCIAL_FLOW: "socialFlow",
    SOCIAL_CONNECT_FROM: "socialConnectFrom",
    ANALYTIC_SESSION_ID: "analyticSessionId",
    DEVICE_INFO: "deviceInfo",
    EVENT_TIMESTAMP: "eventTimestamp",
    IS_SESSION_END_TRIGGERED: "isSessionEndTriggered",
    LOGIN_SESSION_ID: "loginSessionId",
    USER_ID: "userId",
    IP_ADDRESS: "ipAddress",
    USER_LOCATION_DATA: "userLocationData",
    AIRDROP_SESSION_TABS: "sessionTabs",
    AIRDROP_SESSION_TAB_IDENTIFIER: "sessionTabIdentifier",
    AUTH_INITIALIZED_FROM_URL: "authInitializedFromURL",
    IS_NEW_USER: "isNewUser",
    CCP_MODAL_DATA: "CCPModalData",
    CLAN_PAGE_FOR_REGISTRATION: "clanPageForRegistration",
};
exports.SESSION_EVENTS = {
    ANALYTIC_SESSION_START: "analytic_SessionStart",
    ANALYTIC_SESSION_END: "analytic_SessionEnd",
    LOGIN_SUCCESSFUL: "Login_session_start",
    LOGIN_SESSION_END: "login_session_end",
};
exports.ANALYTICS_EVENTS = {
    FIRST_PAGE_LOAD: "first_page_load",
    HOME: { HOME_PAGE_SHOWN: "Homepage_shown" },
    OFFERWALL: {
        VISIT_WEBSITE_CLICK: "OfferwallVisitWebsite_click",
        REDIRECTION_SUCESS: "Offerwallredirection_sucess",
        OVERLAY_SHOW: "Offerwall guide overlay shown",
        PAGE_SHOW: "Offerwall iframe page shown",
        OVERLAY_SPENT_TIME: "Time Spent on the offerwall guide overlay",
        IFRAME_SPENT_TIME: "Time Spent on the offerwall iframe page",
        OVERLAY_CLOSE: "Offerwall guide overlay closed",
    },
    MARKETING_BANNER: {
        CLICK_1: "Marketingbanner1_click",
        CLICK_2: "Marketingbanner2_click",
        CLICK_3: "Marketingbanner3_click",
        CLICK_4: "Marketingbanner4_click",
    },
    GAME_GENRE: {
        TILE: "GameGenreTile_click",
        LIST: "Game Genre Listing Page_shown",
    },
    QUESTS: {
        QUEST_TAB_CLICK: "questtab_click",
        CARD_SHOWN: "Quest card shown",
        LISTING_PAGE_SHOWN: "Quest listing page shown",
        DETAILS_PAGE_SHOWN: "Quest Details page shown",
        QUEST_CARD_CLICK: "questcard_click",
        QUEST_START: "QuestDetailspage_start_click",
        QUEST_SHARE: "questDetailspage_share_click",
        STAGE_SUBMIT: "questDetailspage_submit_click",
        DOWNLOAD_OR_VISIT_WEBSITE: "Questpage_DownloadGame/Visit_click",
        STAGE: {
            EXPENDED: "stage_expand_click",
            MINIMISED: "stage_minimise_click",
        },
        OVERLAY: {
            GAME_DETAILS: {
                LOGIN_METHOD_SELECTED: "GameDetailsOverlay_loginmethod_selected",
                LOGIN_VALUE_INTERACTION: "GameDetailsOverlay_loginvalue_interaction",
                GAME_DETAILS_INTERACTION: "GameDetailsOverlay_gamedetails_interaction",
                LOGIN_SUBMIT: "gamedetailsoverlay_submit_click",
                SUBMISSION_FAIL: "Game Details Submission failed",
                SUBMIT: "Game Details Submitted",
            },
            CLAN_CHIEF: {
                NUMBER_INTERACTION: "clanchiefreferraloverlay_clanchiefnumber_interaction",
                SUBMIT_CLICK: "clanchiefreferraloverlay_submit_click",
                REFERRAL_SHOWN: "Clan chief referral overlay shown",
                ATTRIBUTION_CAPTURED: "Clan chief attribution captured",
                ATTRIBUTION_BYPASSED: "Clan chief attribution bypassed",
                TIME_SPENT: "Time Spent on Clan cheif overlay",
                CLAN_CHIEF_CLOSE: "clanchiefreferraloverlay_crossicon_click",
            },
            UPLOADIMG: {
                SUBMISSION_CAPTURED: "POW submission captured",
                TIME_SPENT: "Time Spent on POW submission overlay",
                SHOWN: "POW submission overlay shown",
                FAILED: "POW submission overlay failed",
                PROOF_UPLOADED: "POWsubmissionoverlay_proof_uploaded",
            },
            PAST_SUBMISSION: {
                CLICK: "questDetailspage_Pastsubmissions_click",
                TIME_SPENT: "Time Spent on past submission overlay",
                SHOWN: "View Past Submissions overlay",
                POW_FAIL: "POW submission failed",
                POW_NEXT_CLICK: "POWsubmissionoverlay_next_click",
            },
            CLOSE_ICON: "POWsubmissionoverlay_crossicon_click",
        },
    },
    LEADERBOARD: {
        WIDGET_CLICK: "Leaderboard_widget_click",
        QUEST_DETAILS_WIDGET_CLICK: "Leaderboard_questdetailswidget_click",
        RANKINGS_SCROLL: "Leaderboard_rankings_scroll",
        INFO_CLICK: "Leaderboard_info_click",
        REWARDS_CLICK: "Leaderboard_Rewards_click",
        REWARDS_SHOWN: "Leaderboard_Rewards_shown",
        INFORMATION_CLICK: "Leaderboard_information_click",
        INFORMATION_SHOWN: "Leaderboard_information_shown",
    },
    CLAN_CHIEF_PROGRAM: {
        PAGE: "View_ClanChiefProgram_Page",
        SUBMIT_FORM: "Submit_ClanChiefProgram_Form",
        CLAN_CREATION: "View_clan_creation_success_overlay",
        CLAN_CREATION_CTA: "Click_clan_creation_success_overlay_CTA",
        CLAN_DASHBOARD: "View_clan_dashboard",
        COPY_INVITE_LINK: "Click_copy_invite_on_clan_dashboard",
        SCROLL_CLAN_TABLE: "Scroll_clan_member_table",
        INVITATION_LINK: "Click_clan_Invitation_Link",
        MY_CLAN_BUTTON: "Click_my_clan_button",
        VIEW_CLAN_INVITATION: "View_clan_invitation_overlay",
        CLAN_INVITATION_CTA: "Click_clan_invitation_overlay_CTA",
        JOIN_CTA: "Click_join_clan_CTA",
        JOIN_SUCCESS: "View_Clan_join_success_overlay",
        JOIN_SUCCESS_CTA: "Click_clan_join_success_overlay_CTA",
        FORM_FIRST_NAME: "Click_Clan_Form_FirstName",
        FORM_EMAIL: "Click_Clan_Form_Email",
        FORM_COUNTRY: "Select_Clan_Form_Country",
        FORM_CITY: "Click_Clan_Form_City",
        FORM_STUDENT: "Select_Clan_Form_IfStudent",
        FORM_COLLEGE_NAME: "Click_Clan_Form_CollegeName",
        SCROLL_CLAN_DASHBOARD: "Scroll_Clan_Dashboard",
        CLICK_VIEW_ALL_MEMBERS: "Click_View_All_Members",
        CLICK_INVITE_MEMBERS: "Click_Invite_Members",
        CLICK_COUNTRY_DROPDOWN: "Click_Select_Country_Dropdown",
        SCROLL_CLAN_CHIEF_PROGRAM_PAGE: "Scroll_ClanChiefProgram_Page",
        CLICK_DELETE_CLAN: "Click_Delete_Clan",
        CLICK_DELETE_CLAN_DELETION_CONFIRMATION_OVERLAY: "Click_Delete_Clan_Deletion_Confirmation_Overlay",
        CLICK_CANCEL_DELETION_CONFIRMATION_OVERLAY: "Click_Cancel_Clan_Deletion_Confirmation_Overlay",
        VIEW_CLAN_DELETION_SUCCESS_OVERLAY: "View_Clan_Deletion_Success_Overlay",
        CLICK_LEAVE_CLAN: "Click_Leave_Clan",
        CLICK_LEAVE_CLAN_LEAVE_CONFIRMATION_OVERLAY: "Click_Leave_Clan_Leave_Confirmation_Overlay",
        CLICK_CANCEL_LEAVE_CONFIRMATION_OVERLAY: "Click_Cancel_Clan_Leave_Confirmation_Overlay",
        VIEW_CLAN_LEAVE_SUCCESS_OVERLAY: "View_Clan_Leave_Success_Overlay",
        VIEW_DELETE_CLAN_OTP_OVERLAY: "View_Delete_Clan_OTP_Overlay",
        CLICK_DELETE_CTA_ON_DELETE_CLAN_OTP_OVERLAY: "Click_DeleteCTA_On_Delete_Clan_OTP_Overlay",
        CLICK_PLAY_CC_ONBOARDING_VIDEO: "Click_Play_CC_Onboarding_Video",
        CLICK_DOWNLOAD_ONBOARDING_KIT_CTA: "Click_Download_Onboarding_Kit_CTA",
        CLICK_CLAN_CHIEF_PROGRAM: "click_clanchiefprogram",
        LEADERBOARD: {
            CLICK_VIEW: "Click_View_Leaderboard",
            SCROLL_TABLE: "Scroll_Leaderboard_Table",
            BOTTOM_SHEET_REWARDS_BUTTON: "Click_Leadearboard_Bottomsheet_Rewards_Button",
            REWARD_DETAILS: "View_Leaderboard_Rewards_Details",
            SCROLL_REWARDS: "Scroll_Leaderboard_Rewards_Details",
            BOTTOM_SHEET_INFORMATION_BUTTON: "Click_Leadearboard_Bottomsheet_Information_Button",
            VIEW_INFORMATION: "View_Leaderboard_Information",
            SCROLL_INFORMATION: "Scrolls_Leaderboard_Information",
            CLOSE_BOTTOM_SHEET: "Close_Leaderboard_Bottomsheet",
            VIEW_RANK_PAGE: "View_leaderboard_RankPage",
            SCROLL_RANK_PAGE: "Scroll_leaderboard_RankPage",
            CLICK_INFO_BUTTON: "Click_Leaderboard_Info_Button",
            CLICK_MY_CLAN_BUTTON: "Click_Leadeboard_MyClan_Button",
            CLICK_GO_BACK_BUTTON: "Click_Leaderboard_GoBack_CTA",
        },
        CLAN_CHIEF_QUEST_BOARD: {
            SCROLL_CLAN_STATS_TABLE: "Scroll_Clan_Stats_Dashboard",
            CLICK_VIEW_DETAILS_BUTTON: "Click_View_Details_Clan_Stats_Dashboard",
            CLICK_SHARE_QUEST_BUTTON: "Click_Share_Quest_Clan_Stats_Dashboard",
            SCROLL_QUEST_STATS_TABLE: "Scroll_Quest_Stats_In_Clan_Stats_Dashboard",
        },
    },
    KCASH: {
        INSUFFICIENT_KCASH: "Insufficientkcashoverlay_Buybutton_click",
        ADD_KCASH: "Addkcashprofile_plusicon_click",
        KCASH_PURCHASE_BTN_CLICK: "kcashpurchasepage_Buybutton_click",
        CONFIRM_KCASH_PURCHASE: "Confirmkcashpurchase_confrimbutton_click",
    },
    PATH_TO_PRO: {
        MENU_ITEM_CLICK: "Klash_Menu_Item_Click",
        HOME_PAGE_STICKY_BANNER_CLICK: "Klash_Home_Page_Sticky_Banner_Click",
        REDIRECTION: "PathToPro_Website_Redirection",
        IGN_POPUP_SHOWN: "IGN_Popup_Shown",
        IGN_SUBMITTED: "IGN_Submitted",
        IGN_HELP_PAGE_SHOWN: "IGN_Help_Page_Shown",
    },
    PROFILE: {
        CLICK_PROFILE_TAB: "Click_Profile_Tab",
        CLICK_CONVERT_ICON: "click Convert icon",
    },
    SESSION_EVENTS: {
        ANALYTIC_SESSION_START: "analytic_SessionStart",
        ANALYTIC_SESSION_END: "analytic_SessionEnd",
        LOGIN_SUCCESSFUL: "Login_session_start",
        LOGIN_SESSION_END: "login_session_end",
    },
    K_STORE: {
        STORE_CLICK_HOMEPAGE: "Store_Click_HomePage",
    },
    LOGIN_EVENTS: {
        OTP_VERIFICATION_OVERLAY_SHOWN: "OTP verification overlay shown",
        SENDOTP_CLICK: "SendOTP_click",
        PHONENUMBERDETAILS_OVERLAY_SHOWN: "Phonenumberdetail-overlay_shown",
        OTPSCREEN_SUBMIT_CLICK: "OTPscreen_Submit_click",
        OTPSCREEN_OTPVERIFICATIONFAILED: "Otpscreen_OTPverificationfailed",
        LOGIN_SESSION_START: "Login_session_start",
        OTP_VERIFICATION_FAILED: "OTP Verification failed",
        OTPSCREEN_RESEND_CLICK: "OTPscreen _Resend_Click",
        OTP_RETRIGGERED: "OTP retriggered",
        CLICK_DISCORD: "click_Discord",
    },
    SOCIAL_LOGIN_EVENTS: {
        CLICK_CONTINUEWITHGOOGLE: "click_ContinuewithGoogle",
        PHONENUMBER_VERIFIFYINITIATED: "phonenumber_verififyinitiated",
        PHONENUMBER_VERIFYCOMPLETED: "phonenumber_verifycompleted",
        EMAIL_VERIFIFYINITIATED: "email_verififyinitiated",
        EMAIL_VERIFIFYCOMPLETED: "email_verififycompleted",
    },
    WEB3AUTH: {
        web3_initiated: "web3_initiated",
        web3_Login_Successfull: "web3_Login_Successfull",
        web3auth_failed: "web3auth_failed",
        web3auth_failed_overlay_shown: "web3auth_failed_overlay_shown",
        walletIdMismatchFoundWithDB: "walletIdMismatchFoundWithDB",
        walletIdSavedInDB: "walletIdSavedInDB",
        web3Auth_connected: "web3Auth_connected",
        PrivateKey_generated_Successfully: "PrivateKey_generated_Successfully",
        web3_initiated_Successfully: "web3_initiated_Successfully",
        Wallet_Created_SuccessFully: "Wallet_Created_SuccessFully",
        Save_Wallet_API_Initiated: "Save_Wallet_API_Initiated",
        Web3_refreshToken_Error: "Web3_refreshToken_Error",
    },
    LOYALTY_JOINING_BONUS_EVENTS: {
        View_Claim_Bonus_Overlay: "View_Claim_Bonus_Overlay",
        Click_Claim_CTA_On_Claim_Bonus_Overlay: "Click_Claim_CTA_On_Claim_Bonus_Overlay",
        Click_Close_On_Claim_Bonus_Overlay: "Click_Close_On_Claim_Bonus_Overlay",
        Click_Know_More_On_Claim_Bonus_Overlay: "Click_Know_More_On_Claim_Bonus_Overlay",
    },
    CCPP_OVERLAY: {
        View_CC_Program_Promotion_Overlay: "View_CC_Program_Promotion_Overlay",
        Click_StartClan_On_CC_Promotion_Overlay: "Click_StartClan_On_CC_Promotion_Overlay",
        Close_CC_Program_Promotion_Overlay: "Close_CC_Program_Promotion_Overlay",
    },
    PROFILE_EVENTS: {
        CLICK_PROFILE_ICON_ON_AIRDROP: "Click_Profile_Icon_On_Airdrop",
        CLICK_PROFILE_CTA_ON_AIRDROP: "Click_Profile_CTA_On_Airdrop",
        CLICK_LOGOUT_CTA_ON_AIRDROP: "Click_Logout_CTA_On_Airdrop",
        CLICK_CONNECT_CTA_ON_AIRDROP_PROFILE: "Click_Connect_CTA_On_Airdrop_Profile",
        VIEW_ERROR_CONNECTING_OVERLAY_ON_AIRDROP_PROFILE: "View_Error_Connecting_Overlay_On_Airdrop_Profile",
        CLICK_RECONNECT_CTA_ON_ERROR_CONNECTING_OVERLAY: "Click_Reconnect_CTA_On_Error_Connecting_Overlay",
        CLOSE_SOCIAL_ALREADY_LINKED_OVERLAY: "Close_social_already_linked_overlay",
        CLICK_CTA_ON_SOCIAL_ALREADY_LINKED_OVERL: "Click_CTA_on_social_already_linked_overl",
    },
    //twitter connect overlay
    TWITTER_CONNECT_EVENTS: {
        OVERLAY_TWITTER_CONNECT_SHOWN: "overlay_twitter_connect_shown",
        OVERLAY_TWITTER_CROSS_BUTTON_CLICK: "overlay_twitter_cross_button_click",
        OVERLAY_TWITTER_CONNECT_CLICK: "overlay_twitter_connect_click",
        OVERLAY_TWITTER_RECONNECT: "overlay_twitter_reconnect",
        OVERLAY_TWITTER_RECONNECT_CROSS_BUTTON_CLICK: "overlay_twitter_recoonect_cross_button_click",
    },
};
